parser: 'babel-eslint'
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
      VariableDeclarator:
        var: 1
        let: 1
        const: 1
  quotes:
    - warn
    - single
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
  no-unused-vars:
    - error
    - args: 'none'
  valid-jsdoc:
    - error
    - prefer:
        arg: param
        argument: param
        returns: return
      preferType:
        Boolean: boolean
        Number: number
        String: string
        Object: object
      requireReturn: false
env:
  browser: true
extends: 'eslint:recommended'
ecmaVersion: 6
parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
plugins:
  - react
